######################################################################
##                                                                  ##
##  LASH NDD package -- v0.9                                        ##
##  ========================                                        ##
##                                                                  ##
##     Makefile.                                                    ##
##                                                                  ##
##     03/13/98  :  Creation. (BB)                                  ##
##     06/09/98  :  Minor corrections. (BB)                         ##
##     07/27/98  :  Addition of 'auto-io'. (BB)                     ##
##     07/28/98  :  Addition of 'auto-basic'. (BB)                  ##
##     08/05/98  :  Addition of 'datastruct'. (BB)                  ##
##     09/04/98  :  Reorganization. (BB)                            ##
##     09/18/98  :  Basic operations. (BB)                          ##
##     09/22/98  :  NDD package. (BB)                               ##
##     09/28/98  :  Reorganization. (BB)                            ##
##     09/29/98  :  New module. (BB)                                ##
##     10/06/98  :  New module. (BB)                                ##
##     10/27/98  :  New module. (BB)                                ##
##     01/05/99  :  New modules. (BB)                               ##
##     01/15/99  :  New module. (BB)                                ##
##     01/20/99  :  New module. (BB)                                ##
##     02/18/99  :  Compilation flag '-ansi'. (BB)                  ##
##     02/22/99  :  New module. (BB)                                ##
##     08/01/00  :  New module. (JMF)                               ##
##     12/10/00  :  New module. (JMF)                               ##
##     18/10/00  :  New module. (LL) (count & biguint)              ##
##     02/24/01  :  Reorganization. (BB)                            ##
##     05/15/01  :  Removed '-Wtraditional' flag. (BB)              ##
##     08/13/01  :  New source tree. (BB)                           ##
##     07/09/02  :  Reorganization. (BB)                            ##
##     02/22/05  :  New module. (LL)                                ##
##                                                                  ##
##  Copyright (c) 1998-2002, Universite de Liege (ULg). All rights  ##
##  reserved. This package is provided for evaluation purposes and  ##
##  educational use only. No guarantee is expressed or implied by   ## 
##  the distribution of this software. The commercial use and the   ##
##  redistribution of this product or of any part of it are not     ##
##  permitted without our prior, express, and written consent.      ##
##                                                                  ##
######################################################################

CC = 		gcc

LASH-LIB-DIR =	../../lib/

LASH-CORE-DIR =	../lash-core/

SRCS-NDD =	ndd.c \
		ndd-sets.c \
		ndd-operations.c \
		ndd-tests.c \
		ndd-equations.c \
		ndd-projection.c \
		ndd-transformations.c \
		ndd-iterations.c \
		ndd-machines.c \
		ndd-io.c \
		ndd-count.c \
		ndd-congruence.c

OBJS-NDD =	${SRCS-NDD:.c=.o}

CFLAGS =   -c -g -O3 -ansi -Wall -Wpointer-arith \
         -Waggregate-return -Wstrict-prototypes \
         -Wmissing-prototypes -Wmissing-declarations \
	 -I$(LASH-CORE-DIR)

all:  ndd-package

ndd-package: $(OBJS-NDD)
	ld -r -o ndd-package.o $(OBJS-NDD) 
	mv ndd-package.o $(LASH-LIB-DIR)

clean:
	-rm -f $(OBJS-NDD) ndd-package.o
	-rm -f $(LASH-LIB-DIR)/ndd-package.o

depend: 
	makedepend -I$(LASH-CORE-DIR) $(SRCS-NDD)

# DO NOT DELETE THIS LINE -- make depend depends on it.

