######################################################################
##                                                                  ##
##  LASH Presburger compiler -- v0.9                                ##
##  ========================                                        ##
##                                                                  ##
##     Makefile.                                                    ##
##                                                                  ##
##     12/14/99  :  Creation. (LL)                                  ##
##     02/12/01  :  Reorganization. (BB)                            ##
##     08/29/02  :  Reorganization. (BB)                            ##
##     05/22/03  :  Added flag for mpatrol. (LL)                    ##
##                                                                  ##
##  Copyright (c) 1998-2002, Universite de Liege (ULg). All rights  ##
##  reserved. This package is provided for evaluation purposes and  ##
##  educational use only. No guarantee is expressed or implied by   ##
##  the distribution of this software. The commercial use and the   ##
##  redistribution of this product or of any part of it are not     ##
##  permitted without our prior, express, and written consent.      ##
##                                                                  ##
######################################################################

CC = 		gcc

LASH-BIN-DIR = 	../../bin
LASH-LIB-DIR = 	../../lib

LASH-CORE-DIR =	../lash-core/
LASH-NDD-DIR  =	../ndd/

LASH-CORE   =	$(LASH-LIB-DIR)/lash-core.o
LASH-ARITH  =   $(LASH-LIB-DIR)/lash-arith.o
NDD-PACKAGE = 	$(LASH-LIB-DIR)/ndd-package.o

SRCS-PRESB =	lexical.c \
		semantic.c \
		expression.c \
		output.c \
		presburger.c

OBJS-PRESB =	${SRCS-PRESB:.c=.o}

CFLAGS =  -g -c -O3 -ansi -Wall -Wtraditional -Wpointer-arith \
         -Waggregate-return -Wstrict-prototypes \
         -Wmissing-prototypes -Wmissing-declarations \
         -I$(LASH-CORE-DIR) -I$(LASH-NDD-DIR) 

all: presburger

presburger: $(OBJS-PRESB)
	$(CC) -g -o presburger $(OBJS-PRESB)\
	 $(LASH-CORE) $(LASH-ARITH) $(NDD-PACKAGE)
	mv presburger $(LASH-BIN-DIR)

clean:
	-rm -f $(OBJS-PRESB) presburger $(LASH-BIN-DIR)/presburger

depend: 
	makedepend -I$(LASH-CORE-DIR) -I$(LASH-NDD-DIR) $(SRCS-PRESB)

# DO NOT DELETE THIS LINE -- make depend depends on it.

