######################################################################
##                                                                  ##
##  LASH QDD package -- v0.9                                        ##
##  ========================                                        ##
##                                                                  ##
##     Makefile.                                                    ##
##                                                                  ##
##     06/30/00  :  Creation. (BB+JMF)                              ##
##     02/12/01  :  Reorganization. (BB)                            ##
##     08/13/01  :  New source tree. (BB)                           ##
##     07/09/02  :  Reorganization. (BB)                            ##
##                                                                  ##
##  Copyright (c) 1998-2002, Universite de Liege (ULg). All rights  ##
##  reserved. This package is provided for evaluation purposes and  ##
##  educational use only. No guarantee is expressed or implied by   ## 
##  the distribution of this software. The commercial use and the   ##
##  redistribution of this product or of any part of it are not     ##
##  permitted without our prior, express, and written consent.      ##
##                                                                  ##
######################################################################

CC = 		gcc

LASH-LIB-DIR =	../../lib/

LASH-CORE-DIR =	../lash-core/

SRCS-QDD =	qdd-one-iterations.c \
                qdd-iterations.c \
                queue-operations.c \
                qdd.c \
                qdd-automaton.c \
                qdd-symbol.c \
                qdd-one-queue.c \
                qdd-perform.c \
                qdd-operations.c \
                qdd-iterations-utils.c \
                qdd-machines.c \
                qdd-io.c

OBJS-QDD =	${SRCS-QDD:.c=.o}

CFLAGS =  -g -c -O3 -ansi -Wall -Wtraditional -Wpointer-arith \
         -Waggregate-return -Wstrict-prototypes \
         -Wmissing-prototypes -Wmissing-declarations \
         -I$(LASH-CORE-DIR)

all:  qdd-package

qdd-package: $(OBJS-QDD)
	ld -r -o qdd-package.o $(OBJS-QDD)
	mv qdd-package.o $(LASH-LIB-DIR)

clean:
	-rm -f $(OBJS-QDD) qdd-package.o
	-rm -f $(LASH-LIB-DIR)/qdd-package.o

depend: 
	makedepend -I$(LASH-CORE-DIR) $(SRCS-QDD)

# DO NOT DELETE THIS LINE -- make depend depends on it.
